---
- hosts: 127.0.0.1
  connection: local
  pre_tasks:
    - name: no recommends for APT
      copy:
        dest: "/etc/apt/apt.conf.d/99_norecommends"
        content: |
          APT::Install-Recommends "false";
          APT::AutoRemove::RecommendsImportant "false";
          APT::AutoRemove::SuggestsImportant "false";

  roles:
    - role: roles/geerlingguy.java
      become: true

    - role: roles/geerlingguy.jenkins
      become: true
      vars:
        jenkins_plugin_timeout: 120
        jenkins_plugins:
          - workflow-aggregator # jenkins pipeline

  tasks:
    - name: Remove caches to trim size
      shell: "rm -rf {{ item }}"
      with_items:
        - /var/lib/apt/lists/*
        - /var/lib/jenkins/updates/default.json
        - /root/.cache
        - /tmp/*
